name: 'parking_semantic_layer'
version: '1.0.0'
config-version: 2

profile: 'parking_semantic_layer'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  parking_semantic_layer:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

seeds:
  parking_semantic_layer:
    +schema: raw
